### ISSUE TITLE
Learn React

### ISSUE THREAD

**Issue by RamaKrishnaReddyVelagala** [RamaKrishnaReddyVelagala/React-Learning#1]
## todo
- [ ] initialize and setup
- [ ] Learn the course contents
- [ ] Build an AirBnb Experiences Clone
- [ ] Build a Meme Generator
- [ ] Build a Notes app and Tenzies Game

**Comment by RamaKrishnaReddyVelagala** [comment]
Description:

##TODO

- [] Initialize the repo locally.
- [] Complete Total course  contents
- [] Build an AirBnb Experiences Clone
- [] Build a Meme Generator
- [] Build a Notes app and Tenzies Game
- [] Finish the glossy work in github to keep everything tidy
