### ISSUE TITLE
learn

### ISSUE THREAD

**Issue by RamaKrishnaReddyVelagala** [RamaKrishnaReddyVelagala/React-Learning#2]
Description:

## Todo
- [ ] Initialize the repo locally.
- [ ] Complete Total course contents
- [ ] Build an AirBnb Experiences Clone
- [ ] Build a Meme Generator
- [ ]Build a Notes app and Tenzies Game
- [ ] Finish the glossy work in github to keep everything tidy
